import "../scss/index.scss";
import "bootstrap-sass";
import "select2";
import "jquery-ui/ui/widgets/autocomplete";
import "./autocomplete";
import "./main";
import "./single-ad";
import "./ads-slider";
import "./modify-ad";
